apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    github.com/project-slug: CarlosCortonCobas/TestRepository
spec:
  type: website
  lifecycle: production
  owner: guest